# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Continuous Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}
      charm-paths:
        description: paths for all charms in this repo
        value: ${{ jobs.get-charm-paths-track.outputs.charm-paths }}
      track:
        description: Charmhub track determined from branch name
        value: ${{ jobs.get-charm-paths-track.outputs.track }}

jobs:
  get-charm-paths-track:
    name: Get charm paths and track
    runs-on: ubuntu-24.04
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
      track: ${{ steps.determine-track.outputs.track }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        uses: canonical/kubeflow-ci/actions/get-charm-paths@main
      - name: Determine track
        id: determine-track
        shell: python
        run: |
          import os

          if "${{ github.event_name }}" == "pull_request":
              ref = "${{ github.base_ref }}"
          else:
              ref = "${{ github.ref_name }}"

          if ref.startswith("track/"):
              track = ref.removeprefix("track/")
          else:
              track = "latest"

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"track={track}\n")

          print(f"Track: {track}")

  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v32.1.0
    permissions:
      contents: read

  lib-check:
    name: Check libraries
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.6.0
        continue-on-error: true
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit

  build:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths-track.outputs.charm-paths) }}
    name: Build charm | ${{ matrix.charm }}
    needs:
      - get-charm-paths-track
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v49.0.1
    with:
      cache: true
      path-to-charm-directory: ${{ matrix.charm }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version (for private repositories)
      contents: read

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - unit-test
      - build
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets: inherit
    permissions:
      contents: write # Needed for Allure Report
